create temporary table TEMP_CDI select * from CORRELATED_DEVICE_INVENTORY where 0;

load data local infile '_~_REPLACE_ME_~_'
  into table TEMP_CDI
  fields terminated by ','
  lines terminated by '\n'
  (MAC_ADDRESS,HFC_GROUP,DEVICE_TYPE,DEVICE_TAG,
   UPDATE_TIME,CM_IP_ADDRESS,MTA_IP_ADDRESS,
   MTA_MAC_ADDRESS,CUSTOM_DATA_1,CUSTOM_DATA_2,
   CUSTOM_DATA_3,CUSTOM_DATA_4,CUSTOM_DATA_5,
   CUSTOM_DATA_6,CUSTOM_DATA_7,CUSTOM_DATA_8,
   CUSTOM_DATA_9,CUSTOM_DATA_10,SUBSCRIBER_PHONE_1,
   SUBSCRIBER_PHONE_2,CMS,CMTS,MTA_ALT_IP_ADDR
  );

load data local infile '_~_REPLACE_ME_~_'
  ignore into table CORRELATED_DEVICE_INVENTORY 
  fields terminated by ','
  lines terminated by '\n'
  (MAC_ADDRESS,HFC_GROUP,DEVICE_TYPE,DEVICE_TAG,
   UPDATE_TIME,CM_IP_ADDRESS,MTA_IP_ADDRESS,
   MTA_MAC_ADDRESS,CUSTOM_DATA_1,CUSTOM_DATA_2,
   CUSTOM_DATA_3,CUSTOM_DATA_4,CUSTOM_DATA_5,
   CUSTOM_DATA_6,CUSTOM_DATA_7,CUSTOM_DATA_8,
   CUSTOM_DATA_9,CUSTOM_DATA_10,SUBSCRIBER_PHONE_1,
   SUBSCRIBER_PHONE_2,CMS,CMTS,MTA_ALT_IP_ADDR
  );

update CORRELATED_DEVICE_INVENTORY cdi, TEMP_CDI temp
  set 
    cdi.HFC_GROUP=temp.HFC_GROUP,
    cdi.DEVICE_TYPE=temp.DEVICE_TYPE,
    cdi.DEVICE_TAG=temp.DEVICE_TAG,
    cdi.UPDATE_TIME=temp.UPDATE_TIME,
    cdi.CM_IP_ADDRESS=temp.CM_IP_ADDRESS,
    cdi.MTA_IP_ADDRESS=temp.MTA_IP_ADDRESS,
    cdi.MTA_MAC_ADDRESS=temp.MTA_MAC_ADDRESS,
    cdi.CUSTOM_DATA_1=temp.CUSTOM_DATA_1,
    cdi.CUSTOM_DATA_2=temp.CUSTOM_DATA_2,
    cdi.CUSTOM_DATA_3=temp.CUSTOM_DATA_3,
    cdi.CUSTOM_DATA_4=temp.CUSTOM_DATA_4,
    cdi.CUSTOM_DATA_5=temp.CUSTOM_DATA_5,
    cdi.CUSTOM_DATA_6=temp.CUSTOM_DATA_6,
    cdi.CUSTOM_DATA_7=temp.CUSTOM_DATA_7,
    cdi.CUSTOM_DATA_8=temp.CUSTOM_DATA_8,
    cdi.CUSTOM_DATA_9=temp.CUSTOM_DATA_9,
    cdi.CUSTOM_DATA_10=temp.CUSTOM_DATA_10,
    cdi.SUBSCRIBER_PHONE_1=temp.SUBSCRIBER_PHONE_1,
    cdi.SUBSCRIBER_PHONE_2=temp.SUBSCRIBER_PHONE_2,
    cdi.CMS=temp.CMS,
    cdi.CMTS=temp.CMTS,
    cdi.UPDATE_TIME=NOW()
  where cdi.MAC_ADDRESS=temp.MAC_ADDRESS;

update CORRELATED_DEVICE_INVENTORY cdi, TEMP_CDI temp
  set
    cdi.MTA_ALT_IP_ADDR=temp.MTA_ALT_IP_ADDR
  where cdi.MAC_ADDRESS=temp.MAC_ADDRESS and temp.MAC_ADDRESS is not NULL
    and (cdi.MAC_ADDRESS is NULL or cdi.MAC_ADDRESS="");

update CORRELATED_DEVICE_INVENTORY cor, CMEX_MODEM_INVENTORY modem
  set cor.CM_IP_ADDRESS=modem.MODEM_IP_ADDRESS
  where cor.MAC_ADDRESS=modem.MAC_ADDRESS;

update CORRELATED_DEVICE_INVENTORY cor
  set 
    cor.DEVICE_TYPE='XPDR',
    cor.HFC_GROUP=NULL
  where cor.HFC_GROUP='trans';
