
/*==============================================================*/
/* Table : QWEST_SEPTEMBER                                           */
/*==============================================================*/


create table QWEST_DECEMBER  (
   CALL_SERVICE_TYPE    varchar2(2),
   COMPONENT_GROUP_CD   varchar2(2),
   COMPONENT_GRP_VAL    VARCHAR2(24),
   PRODUCT_ACCT_ID      varchar2(12),
   CUSTOMER_NUMBER      varchar2(10),
   ORIG_DT              varchar2(8),
   DISCN_DT             varchar2(8),
   ORIG_TIME            varchar2(6),
   DISCN_TIME           varchar2(6),
   CALL_DURATION_MINUTES varchar2(5),
   CALL_DURATION_SECONDS varchar2(2),
   DIALEDNO             varchar2(15),
   CALLEDNO             varchar2(15),
   ANI                  varchar2(15),
   ANSTYPE              varchar2(6),
   PINDIGS              varchar2(4),
   INFODIG              varchar2(2),
   SURCHARGE            varchar2(1),
   COMPCODE             varchar2(6),
   PREDIG               varchar2(1),
   TRTMTCD              varchar2(6),
   ORIG_TRUNK_GROUP_NAME varchar2(12),
   ORIGMEM              varchar2(6),
   TERM_TRUNK_GROUP_NAME varchar2(12),
   TERMMEM              varchar2(6),
   INTRA_LATA_IND       varchar2(1),
   CALL_AREA            varchar2(1),
   CITY_CALLING         varchar2(10),
   STATE_CALLING        varchar2(2),
   CITY_CALLED          varchar2(10),
   STATE_CALLED         varchar2(2),
   RATE_PERIOD          varchar2(1),
   TERMINATING_COUNTRY_CODE varchar2(4),
   ORIGINATING_COUNTRY_CODE varchar2(4),
   PAC_CODES            varchar2(12),
   ORIG_PRICING_NPA     varchar2(3),
   ORIG_PRICING_NXX     varchar2(3),
   TERM_PRICING_NPA     varchar2(3),
   TERM_PRICING_NXX     varchar2(3),
   AUTHORIZATION_CODE_FULL varchar2(14),
   UNIVACC              varchar2(10),
   PRCMP_ID             varchar2(6),
   CARRSEL              varchar2(1),
   CIC                  varchar2(6),
   ORIGLRN              varchar2(10),
   PORTEDNO             varchar2(10),
   LNPCHECK             varchar2(1),
   ORIGINATING_IDDD_CITY_CODE varchar2(8),
   TERMINATING_IDDD_CITY_CODE varchar2(8),
   ORIGINATING_LATA     varchar2(4),
   TERMINATING_LATA     varchar2(4),
   CLASS_TYPE           varchar2(2),
   MEXICO_RATE_STEP     varchar2(2),
   ESTIMATED_CHARGE     varchar2(6),
   BILLING_OCN          varchar2(4),
   ORIG_TERM_CODE       varchar2(1),
   CLGPTYNO             varchar2(15),
   CLGPTYNO_IDENTIFIER  varchar2(1),
   ORIG_OCN             varchar2(4),
   TERM_OCN             varchar2(4),
   UNROUNDED_PRICE      varchar2(10),
   RATE_PER_MINUTE      varchar2(8),
   FINSID               varchar2(6),
   FINAL_TRUNK_GROUP_NAME varchar2(12),
   CARRIAGE_RETURN      varchar2(1)
)
/



