DROP TABLE IPTELMGR.STREET_SUFFIX CASCADE CONSTRAINTS;

CREATE TABLE IPTELMGR.STREET_SUFFIX ( PRIMARY_SUFFIX VARCHAR2(15 BYTE), COMMON_SUFFIX VARCHAR2(15 BYTE), POSTAL_SUFFIX VARCHAR2(15 BYTE) ) TABLESPACE IPTELD PCTUSED 40 PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 48K NEXT 16M MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT ) LOGGING NOCOMPRESS NOCACHE NOPARALLEL MONITORING;

Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ALLEY', 'ALLEY', 'ALY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ALLEY', 'ALLY', 'ALY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ALLEY', 'ALY', 'ALY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ANNEX', 'ANEX', 'ANX');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ANNEX', 'ANNEX', 'ANX');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ANNEX', 'ANNX', 'ANX');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ANNEX', 'ANX', 'ANX');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ARCADE', 'ARC', 'ARC');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ARCADE', 'ARCADE', 'ARC');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('AVENUE', 'AV', 'AV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('AVENUE', 'AVE', 'AVE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('AVENUE', 'AVEN', 'AVE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('AVENUE', 'AVENU', 'AVE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('AVENUE', 'AVENUE', 'AVE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('AVENUE', 'AVN', 'AVE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('AVENUE', 'AVNUE', 'AVE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('AVENUE', 'AV', 'AVE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('AVENUE', 'AVE', 'AV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BAYOO', 'BAYOO', 'BYU');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BAYOO', 'BAYOU', 'BYU');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BEACH', 'BCH', 'BCH');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BEACH', 'BEACH', 'BCH');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BEND', 'BEND', 'BND');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BEND', 'BND', 'BND');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BLUFF', 'BLF', 'BLF');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BLUFF', 'BLUF', 'BLF');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BLUFF', 'BLUFF', 'BLF');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BLUFFS', 'BLUFFS', 'BLFS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BOTTOM', 'BOT', 'BTM');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ALLEY', 'ALLEE', 'ALY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BOTTOM', 'BOTTM', 'BTM');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BOTTOM', 'BOTTOM', 'BTM');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BOTTOM', 'BTM', 'BTM');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BOULEVARD', 'BLVD', 'BLVD');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BOULEVARD', 'BOUL', 'BLVD');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BOULEVARD', 'BOULEVARD', 'BLVD');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BOULEVARD', 'BOULV', 'BLVD');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BOULEVARD', 'BL', 'BLVD');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BRANCH', 'BR', 'BR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BRANCH', 'BRANCH', 'BR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BRANCH', 'BRNCH', 'BR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BRIDGE', 'BRDGE', 'BRG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BRIDGE', 'BRG', 'BRG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BRIDGE', 'BRIDGE', 'BRG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BROOK', 'BRK', 'BRK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BROOK', 'BROOK', 'BRK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BROOKS', 'BROOKS', 'BRKS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BURG', 'BURG', 'BG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BURGS', 'BURGS', 'BGS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BYPASS', 'BYP', 'BYP');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BYPASS', 'BYPA', 'BYP');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BYPASS', 'BYPAS', 'BYP');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BYPASS', 'BYPASS', 'BYP');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('BYPASS', 'BYPS', 'BYP');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CAMP', 'CAMP', 'CP');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CAMP', 'CMP', 'CP');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CAMP', 'CP', 'CP');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CANYON', 'CANYN', 'CYN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CANYON', 'CANYON', 'CYN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CANYON', 'CNYN', 'CYN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CANYON', 'CYN', 'CYN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CAPE', 'CAPE', 'CPE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CAPE', 'CPE', 'CPE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CAUSEWAY', 'CAUSEWAY', 'CSWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CAUSEWAY', 'CAUSWAY', 'CSWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CAUSEWAY', 'CSWY', 'CSWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CENTER', 'CEN', 'CTR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CENTER', 'CENT', 'CTR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CENTER', 'CENTER', 'CTR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CENTER', 'CENTR', 'CTR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CENTER', 'CENTRE', 'CTR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CENTER', 'CNTER', 'CTR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CENTER', 'CNTR', 'CTR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CENTER', 'CTR', 'CTR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CENTERS', 'CENTERS', 'CTRS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CIRCLE', 'CIR', 'CIR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CIRCLE', 'CIRC', 'CIR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CIRCLE', 'CIRCL', 'CIR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CIRCLE', 'CIRCLE', 'CIR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CIRCLE', 'CRCL', 'CIR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CIRCLE', 'CRCLE', 'CIR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CIRCLES', 'CIRCLES', 'CIRS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CLIFF', 'CLF', 'CLF');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CLIFF', 'CLIFF', 'CLF');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CLIFFS', 'CLFS', 'CLFS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CLIFFS', 'CLIFFS', 'CLFS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CLUB', 'CLB', 'CLB');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CLUB', 'CLUB', 'CLB');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('COMMON', 'COMMON', 'CMN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CORNER', 'COR', 'COR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CORNER', 'CORNER', 'COR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CORNERS', 'CORNERS', 'CORS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CORNERS', 'CORS', 'CORS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('COURSE', 'COURSE', 'CRSE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('COURSE', 'CRSE', 'CRSE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('COURT', 'COURT', 'CT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('COURT', 'CRT', 'CT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('COURT', 'CT', 'CT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('COURTS', 'COURTS', 'CTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('COURTS', 'CTS', 'CTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('COVE', 'COVE', 'CV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('COVE', 'CV', 'CV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('COVES', 'COVES', 'CVS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CREEK', 'CK', 'CRK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CREEK', 'CR', 'CRK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CREEK', 'CREEK', 'CRK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CREEK', 'CRK', 'CRK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CRESCENT', 'CRECENT', 'CRES');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CRESCENT', 'CRES', 'CRES');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CRESCENT', 'CRESCENT', 'CRES');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CRESCENT', 'CRESENT', 'CRES');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CRESCENT', 'CRSCNT', 'CRES');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CRESCENT', 'CRSENT', 'CRES');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CRESCENT', 'CRSNT', 'CRES');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CREST', 'CREST', 'CRST');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CROSSING', 'CROSSING', 'XING');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CROSSING', 'CRSSING', 'XING');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CROSSING', 'CRSSNG', 'XING');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CROSSING', 'XING', 'XING');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CROSSROAD', 'CROSSROAD', 'XRD');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CURVE', 'CURVE', 'CURV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('DALE', 'DALE', 'DL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('DALE', 'DL', 'DL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('DAM', 'DAM', 'DM');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('DAM', 'DM', 'DM');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('DIVIDE', 'DIV', 'DV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('DIVIDE', 'DIVIDE', 'DV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('DIVIDE', 'DV', 'DV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('DIVIDE', 'DVD', 'DV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('DRIVE', 'DR', 'DR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('DRIVE', 'DRIV', 'DR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('DRIVE', 'DRIVE', 'DR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('DRIVE', 'DRV', 'DR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('DRIVES', 'DRIVES', 'DRS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ESTATE', 'EST', 'EST');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ESTATE', 'ESTATE', 'EST');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ESTATES', 'ESTATES', 'ESTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ESTATES', 'ESTS', 'ESTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('EXPRESSWAY', 'EXP', 'EXPY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('EXPRESSWAY', 'EXPR', 'EXPY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('EXPRESSWAY', 'EXPRESS', 'EXPY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('EXPRESSWAY', 'EXPRESSWAY', 'EXPY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('EXPRESSWAY', 'EXPW', 'EXPY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('EXPRESSWAY', 'EXPY', 'EXPY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('EXPRESSWAY', 'EXPWY', 'EXPY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('EXTENSION', 'EXT', 'EXT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('EXTENSION', 'EXTENSION', 'EXT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('EXTENSION', 'EXTN', 'EXT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('EXTENSION', 'EXTNSN', 'EXT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('EXTENSIONS', 'EXTENSIONS', 'EXTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('EXTENSIONS', 'EXTS', 'EXTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FALL', 'FALL', 'FALL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FALLS', 'FALLS', 'FLS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FALLS', 'FLS', 'FLS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FERRY', 'FERRY', 'FRY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FERRY', 'FRRY', 'FRY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FERRY', 'FRY', 'FRY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FIELD', 'FIELD', 'FLD');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FIELD', 'FLD', 'FLD');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FIELDS', 'FIELDS', 'FLDS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FIELDS', 'FLDS', 'FLDS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FLAT', 'FLAT', 'FLT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FLAT', 'FLT', 'FLT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FLATS', 'FLATS', 'FLTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FLATS', 'FLTS', 'FLTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FORD', 'FORD', 'FRD');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FORD', 'FRD', 'FRD');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FORDS', 'FORDS', 'FRDS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FOREST', 'FOREST', 'FRST');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FOREST', 'FORESTS', 'FRST');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FOREST', 'FRST', 'FRST');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FORGE', 'FORG', 'FRG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FORGE', 'FORGE', 'FRG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FORGE', 'FRG', 'FRG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FORGES', 'FORGES', 'FRGS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FORK', 'FORK', 'FRK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FORK', 'FRK', 'FRK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FORKS', 'FORKS', 'FRKS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FORKS', 'FRKS', 'FRKS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FORT', 'FORT', 'FT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FORT', 'FRT', 'FT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FORT', 'FT', 'FT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FREEWAY', 'FREEWAY', 'FWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FREEWAY', 'FREEWY', 'FWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FREEWAY', 'FRWAY', 'FWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FREEWAY', 'FRWY', 'FWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('FREEWAY', 'FWY', 'FWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GARDEN', 'GARDEN', 'GDN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GARDEN', 'GARDN', 'GDN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GARDEN', 'GDN', 'GDN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GARDEN', 'GRDEN', 'GDN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GARDEN', 'GRDN', 'GDN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GARDENS', 'GARDENS', 'GDNS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GARDENS', 'GDNS', 'GDNS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GARDENS', 'GRDNS', 'GDNS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GATE', 'GT', 'GATE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GATEWAY', 'GATEWAY', 'GTWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GATEWAY', 'GATEWY', 'GTWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GATEWAY', 'GATWAY', 'GTWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GATEWAY', 'GTWAY', 'GTWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GATEWAY', 'GTWY', 'GTWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GLEN', 'GLEN', 'GLN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GLEN', 'GLN', 'GLN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GLENS', 'GLENS', 'GLNS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GREEN', 'GREEN', 'GRN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GREEN', 'GRN', 'GRN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GREENS', 'GREENS', 'GRNS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GROVE', 'GROV', 'GRV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GROVE', 'GROVE', 'GRV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GROVE', 'GRV', 'GRV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('GROVES', 'GROVES', 'GRVS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HARBOR', 'HARB', 'HBR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HARBOR', 'HARBOR', 'HBR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HARBOR', 'HARBR', 'HBR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HARBOR', 'HBR', 'HBR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HARBOR', 'HRBOR', 'HBR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HARBORS', 'HARBORS', 'HBRS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HAVEN', 'HAVEN', 'HVN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HAVEN', 'HAVN', 'HVN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HAVEN', 'HVN', 'HVN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HEIGHTS', 'HEIGHT', 'HTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HEIGHTS', 'HEIGHTS', 'HTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HEIGHTS', 'HGTS', 'HTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HEIGHTS', 'HT', 'HTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HEIGHTS', 'HTS', 'HTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HIGHWAY', 'HIGHWAY', 'HWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HIGHWAY', 'HIGHWY', 'HWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HIGHWAY', 'HIWAY', 'HWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HIGHWAY', 'HIWY', 'HWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HIGHWAY', 'HWAY', 'HWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HIGHWAY', 'HWY', 'HWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HILL', 'HILL', 'HL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HILL', 'HL', 'HL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HILLS', 'HILLS', 'HLS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HILLS', 'HLS', 'HLS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HOLLOW', 'HLLW', 'HOLW');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HOLLOW', 'HOLLOW', 'HOLW');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HOLLOW', 'HOLLOWS', 'HOLW');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HOLLOW', 'HOLW', 'HOLW');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HOLLOW', 'HOLWS', 'HOLW');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('INLET', 'INLET', 'INLT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('INLET', 'INLT', 'INLT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ISLAND', 'IS', 'IS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ISLAND', 'ISLAND', 'IS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ISLAND', 'ISLND', 'IS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ISLANDS', 'ISLANDS', 'ISS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ISLANDS', 'ISLNDS', 'ISS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ISLANDS', 'ISS', 'ISS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ISLE', 'ISLE', 'ISLE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ISLE', 'ISLES', 'ISLE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('JUNCTION', 'JCT', 'JCT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('JUNCTION', 'JCTION', 'JCT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('JUNCTION', 'JCTN', 'JCT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('JUNCTION', 'JUNCTION', 'JCT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('JUNCTION', 'JUNCTN', 'JCT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('JUNCTION', 'JUNCTON', 'JCT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('JUNCTIONS', 'JCTNS', 'JCTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('JUNCTIONS', 'JCTS', 'JCTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('JUNCTIONS', 'JUNCTIONS', 'JCTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('KEY', 'KEY', 'KY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('KEY', 'KY', 'KY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('KEYS', 'KEYS', 'KYS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('KEYS', 'KYS', 'KYS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('KNOLL', 'KNL', 'KNL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('KNOLL', 'KNOL', 'KNL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('KNOLL', 'KNOLL', 'KNL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('KNOLLS', 'KNLS', 'KNLS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('KNOLLS', 'KNOLLS', 'KNLS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LAKE', 'LAKE', 'LK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LAKE', 'LK', 'LK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LAKES', 'LAKES', 'LKS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LAKES', 'LKS', 'LKS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LAND', 'LAND', 'LAND');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LANDING', 'LANDING', 'LNDG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LANDING', 'LNDG', 'LNDG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LANDING', 'LNDNG', 'LNDG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LANE', 'LA', 'LN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LANE', 'LANE', 'LN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LANE', 'LANES', 'LN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LANE', 'LN', 'LN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LIGHT', 'LGT', 'LGT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LIGHT', 'LIGHT', 'LGT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LIGHTS', 'LIGHTS', 'LGTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LOAF', 'LF', 'LF');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LOAF', 'LOAF', 'LF');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LOCK', 'LCK', 'LCK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LOCK', 'LOCK', 'LCK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LOCKS', 'LCKS', 'LCKS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LOCKS', 'LOCKS', 'LCKS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LODGE', 'LDG', 'LDG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LODGE', 'LDGE', 'LDG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LODGE', 'LODG', 'LDG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LODGE', 'LODGE', 'LDG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LOOP', 'LOOP', 'LOOP');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LOOP', 'LOOPS', 'LOOP');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MALL', 'MALL', 'MALL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MANOR', 'MANOR', 'MNR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MANOR', 'MNR', 'MNR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MANORS', 'MANORS', 'MNRS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MANORS', 'MNRS', 'MNRS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MEADOW', 'MDW', 'MDW');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MEADOW', 'MEADOW', 'MDW');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MEADOWS', 'MDWS', 'MDWS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MEADOWS', 'MEADOWS', 'MDWS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MEADOWS', 'MEDOWS', 'MDWS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MEWS', 'MEWS', 'MEWS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MILL', 'MILL', 'ML');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MILL', 'ML', 'ML');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MILLS', 'MILLS', 'MLS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MILLS', 'MLS', 'MLS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MISSION', 'MISSION', 'MSN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MISSION', 'MISSN', 'MSN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MISSION', 'MSN', 'MSN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MISSION', 'MSSN', 'MSN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MOTORWAY', 'MOTORWAY', 'MTWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MOUNT', 'MNT', 'MT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MOUNT', 'MOUNT', 'MT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MOUNT', 'MT', 'MT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MOUNTAIN', 'MNTAIN', 'MTN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MOUNTAIN', 'MNTN', 'MTN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MOUNTAIN', 'MOUNTAIN', 'MTN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MOUNTAIN', 'MOUNTIN', 'MTN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MOUNTAIN', 'MTIN', 'MTN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MOUNTAIN', 'MTN', 'MTN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MOUNTAINS', 'MNTNS', 'MTNS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MOUNTAINS', 'MOUNTAINS', 'MTNS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('NECK', 'NCK', 'NCK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('NECK', 'NECK', 'NCK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ORCHARD', 'ORCH', 'ORCH');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ORCHARD', 'ORCHARD', 'ORCH');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ORCHARD', 'ORCHRD', 'ORCH');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('OVAL', 'OVAL', 'OVAL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('OVAL', 'OVL', 'OVAL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('OVERPASS', 'OVERPASS', 'OPAS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PARK', 'PARK', 'PARK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PARK', 'PK', 'PARK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PARK', 'PRK', 'PARK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PARKS', 'PARKS', 'PARK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PARKWAY', 'PARKWAY', 'PKWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PARKWAY', 'PARKWY', 'PKWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PARKWAY', 'PKWAY', 'PKWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PARKWAY', 'PKWY', 'PKWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PARKWAY', 'PKY', 'PKWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PARKWAYS', 'PARKWAYS', 'PKWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PARKWAYS', 'PKWYS', 'PKWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PASS', 'PASS', 'PASS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PASSAGE', 'PASSAGE', 'PSGE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PATH', 'PATH', 'PATH');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PATH', 'PATHS', 'PATH');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PIKE', 'PIKE', 'PIKE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PIKE', 'PIKES', 'PIKE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PINE', 'PINE', 'PNE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PINES', 'PINES', 'PNES');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PINES', 'PNES', 'PNES');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PLACE', 'PL', 'PL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PLACE', 'PLACE', 'PL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PLAIN', 'PLAIN', 'PLN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PLAIN', 'PLN', 'PLN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PLAINS', 'PLAINES', 'PLNS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PLAINS', 'PLAINS', 'PLNS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PLAINS', 'PLNS', 'PLNS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PLAZA', 'PLAZA', 'PLZ');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PLAZA', 'PLZ', 'PLZ');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PLAZA', 'PLZA', 'PLZ');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('POINT', 'POINT', 'PT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('POINT', 'PT', 'PT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('POINTS', 'POINTS', 'PTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('POINTS', 'PTS', 'PTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PORT', 'PORT', 'PRT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PORT', 'PRT', 'PRT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PORTS', 'PORTS', 'PRTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PORTS', 'PRTS', 'PRTS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PRAIRIE', 'PR', 'PR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PRAIRIE', 'PRAIRIE', 'PR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PRAIRIE', 'PRARIE', 'PR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PRAIRIE', 'PRR', 'PR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PRIMARY_SUFFIX', 'COMMON_SUFFIX', 'POSTAL_SUFFIX');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RADIAL', 'RAD', 'RADL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RADIAL', 'RADIAL', 'RADL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RADIAL', 'RADIEL', 'RADL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RADIAL', 'RADL', 'RADL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RAMP', 'RAMP', 'RAMP');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RANCH', 'RANCH', 'RNCH');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RANCH', 'RANCHES', 'RNCH');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RANCH', 'RNCH', 'RNCH');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RANCH', 'RNCHS', 'RNCH');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RAPID', 'RAPID', 'RPD');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RAPID', 'RPD', 'RPD');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RAPIDS', 'RAPIDS', 'RPDS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RAPIDS', 'RPDS', 'RPDS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('REST', 'REST', 'RST');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('REST', 'RST', 'RST');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RIDGE', 'RDG', 'RDG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RIDGE', 'RDGE', 'RDG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RIDGE', 'RIDGE', 'RDG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RIDGES', 'RDGS', 'RDGS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RIDGES', 'RIDGES', 'RDGS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RIVER', 'RIV', 'RIV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RIVER', 'RIVER', 'RIV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RIVER', 'RIVR', 'RIV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RIVER', 'RVR', 'RIV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ROAD', 'RD', 'RD');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ROAD', 'ROAD', 'RD');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ROADS', 'RDS', 'RDS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ROADS', 'ROADS', 'RDS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ROADWAY', 'RDWY', 'RDWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ROUTE', 'ROUTE', 'RTE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ROW', 'ROW', 'ROW');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RUE', 'RUE', 'RUE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('RUN', 'RUN', 'RUN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SHOAL', 'SHL', 'SHL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SHOAL', 'SHOAL', 'SHL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SHOALS', 'SHLS', 'SHLS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SHOALS', 'SHOALS', 'SHLS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SHORE', 'SHOAR', 'SHR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SHORE', 'SHORE', 'SHR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SHORE', 'SHR', 'SHR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SHORES', 'SHOARS', 'SHRS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SHORES', 'SHORES', 'SHRS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SHORES', 'SHRS', 'SHRS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SKYWAY', 'SKYWAY', 'SKWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SPRING', 'SPG', 'SPG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SPRING', 'SPNG', 'SPG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SPRING', 'SPRING', 'SPG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SPRING', 'SPRNG', 'SPG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SPRINGS', 'SPGS', 'SPGS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SPRINGS', 'SPNGS', 'SPGS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SPRINGS', 'SPRINGS', 'SPGS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SPRINGS', 'SPRNGS', 'SPGS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SPUR', 'SPUR', 'SPUR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SPURS', 'SPURS', 'SPUR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SQUARE', 'SQ', 'SQ');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SQUARE', 'SQR', 'SQ');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SQUARE', 'SQRE', 'SQ');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SQUARE', 'SQU', 'SQ');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SQUARE', 'SQUARE', 'SQ');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SQUARES', 'SQRS', 'SQS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SQUARES', 'SQUARES', 'SQS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STATION', 'STA', 'STA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STATION', 'STATION', 'STA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STATION', 'STATN', 'STA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STATION', 'STN', 'STA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STRAVENUE', 'STRA', 'STRA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STRAVENUE', 'STRAV', 'STRA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STRAVENUE', 'STRAVE', 'STRA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STRAVENUE', 'STRAVEN', 'STRA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STRAVENUE', 'STRAVENUE', 'STRA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STRAVENUE', 'STRAVN', 'STRA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STRAVENUE', 'STRVN', 'STRA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STRAVENUE', 'STRVNUE', 'STRA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STREAM', 'STREAM', 'STRM');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STREAM', 'STREME', 'STRM');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STREAM', 'STRM', 'STRM');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STREET', 'ST', 'ST');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STREET', 'STR', 'ST');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STREET', 'STREET', 'ST');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STREET', 'STRT', 'ST');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('STREETS', 'STREETS', 'STS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SUMMIT', 'SMT', 'SMT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SUMMIT', 'SUMIT', 'SMT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SUMMIT', 'SUMITT', 'SMT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('SUMMIT', 'SUMMIT', 'SMT');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TERRACE', 'TER', 'TER');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TERRACE', 'TERR', 'TER');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TERRACE', 'TERRACE', 'TER');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('THROUGHWAY', 'THROUGHWAY', 'TRWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRACE', 'TRACE', 'TRCE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRACE', 'TRACES', 'TRCE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRACE', 'TRCE', 'TRCE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRACK', 'TRACK', 'TRAK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRACK', 'TRACKS', 'TRAK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRACK', 'TRAK', 'TRAK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRACK', 'TRK', 'TRAK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRACK', 'TRKS', 'TRAK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRAFFICWAY', 'TRAFFICWAY', 'TRFY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRAFFICWAY', 'TRFY', 'TRFY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRAIL', 'TR', 'TRL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRAIL', 'TRAIL', 'TRL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRAIL', 'TRAILS', 'TRL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRAIL', 'TRL', 'TRL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRAIL', 'TRLS', 'TRL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TUNNEL', 'TUNEL', 'TUNL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TUNNEL', 'TUNL', 'TUNL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TUNNEL', 'TUNLS', 'TUNL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TUNNEL', 'TUNNEL', 'TUNL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TUNNEL', 'TUNNELS', 'TUNL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TUNNEL', 'TUNNL', 'TUNL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TURNPIKE', 'TPK', 'TPKE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TURNPIKE', 'TPKE', 'TPKE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TURNPIKE', 'TRNPK', 'TPKE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TURNPIKE', 'TRPK', 'TPKE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TURNPIKE', 'TURNPIKE', 'TPKE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TURNPIKE', 'TURNPK', 'TPKE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TURNPIKE', 'TPKE', 'TRNPK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('UNDERPASS', 'UNDERPASS', 'UPAS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('UNION', 'UN', 'UN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('UNION', 'UNION', 'UN');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('UNIONS', 'UNIONS', 'UNS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VALLEY', 'VALLEY', 'VLY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VALLEY', 'VALLY', 'VLY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VALLEY', 'VLLY', 'VLY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VALLEY', 'VLY', 'VLY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VALLEYS', 'VALLEYS', 'VLYS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VALLEYS', 'VLYS', 'VLYS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VIADUCT', 'VDCT', 'VIA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VIADUCT', 'VIA', 'VIA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VIADUCT', 'VIADCT', 'VIA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VIADUCT', 'VIADUCT', 'VIA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VIEW', 'VIEW', 'VW');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VIEW', 'VW', 'VW');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VIEWS', 'VIEWS', 'VWS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VIEWS', 'VWS', 'VWS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VILLAGE', 'VILL', 'VLG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VILLAGE', 'VILLAG', 'VLG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VILLAGE', 'VILLAGE', 'VLG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VILLAGE', 'VILLG', 'VLG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VILLAGE', 'VILLIAGE', 'VLG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VILLAGE', 'VLG', 'VLG');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VILLAGES', 'VILLAGES', 'VLGS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VILLAGES', 'VLGS', 'VLGS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VILLE', 'VILLE', 'VL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VILLE', 'VL', 'VL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VISTA', 'VIS', 'VIS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VISTA', 'VIST', 'VIS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VISTA', 'VISTA', 'VIS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VISTA', 'VST', 'VIS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('VISTA', 'VSTA', 'VIS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('WALK', 'WALK', 'WALK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('WALKS', 'WALKS', 'WALK');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('WALL', 'WALL', 'WALL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('WAY', 'WAY', 'WAY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('WAY', 'WY', 'WAY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('WAYS', 'WAYS', 'WAYS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('WELL', 'WELL', 'WL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('WELLS', 'WELLS', 'WLS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('WELLS', 'WLS', 'WLS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ROAD', 'RD', 'ROAD');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('AVENUE', 'AV', 'AVENUE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('AVENUE', 'AVE', 'AVENUE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('AVENUE', 'AVENUE', 'AV');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CIRCLE', 'CI', 'CIR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CIRCLE', 'CI', 'CIRCLE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CIRCLE', 'CIR', 'CI');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CIRCLE', 'CIR', 'CIRCLE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CIRCLE', 'CIRCLE', 'CI');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('COMMONS', 'COMMONS', 'CMNS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('CROSSROADS', 'CROSSROADS', 'XRDS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('DRIVE', 'D', 'DR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HIGHWAY', 'HW', 'HWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('HIGHWAY', 'HWY', 'HW');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LANE', 'LA', 'LANE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LANE', 'LANE', 'LA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LANE', 'LN', 'LA');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('LANE', 'LN', 'LANE');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('MEADOWS', 'MDW', 'MDWS');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('PARKWAY', 'PW', 'PKWY');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('ROAD', 'R', 'ROAD');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TERRACE', 'TE', 'TER');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRAIL', 'TL', 'TRL');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRAILER', 'TRAILER', 'TRLR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRAILER', 'TRLR', 'TRLR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TRAILER', 'TRLRS', 'TRLR');
Insert into STREET_SUFFIX
   (PRIMARY_SUFFIX, COMMON_SUFFIX, POSTAL_SUFFIX)
 Values
   ('TURNPIKE', 'TP', 'TPKE');
COMMIT;
