REF_NTWK_CMPNT_TYP                     10                                       
REF_INSTANCE_STATUS                    10                                       
REF_CMPNT_INSTANCE                     10                                       
REF_PROJ_STATUS                        10                                       
REF_CONTROL_STATUS                     11                                       
REF_ATTR                               12                                       
REF_ORDR_TYP                           13                                       
REF_SUB_STATUS                         13                                       
REF_SUB_SVC_STATUS                     13                                       
REF_ORDR_ITEM_STATUS                   13                                       
TECH_PLATFORM_PARM                     14                                       
REF_ORDR_ACTION                        17                                       
SBNT_TECH_PLATFORM                     17                                       
REF_EVENT                              19                                       
REF_ASSOC_TYP                          19                                       
REF_ORDR_STATUS                        20                                       
PROJ_TRANSITIONS                       21                                       
PROJ_TMPLT                             22                                       
TASK_TMPLT_DEPY                        22                                       
REF_STATUS_CHG_REASON                  22                                       
MANUAL_TASK_LOG                        23                                       
TASK_TMPLT                             24                                       
PROJ_TMPLT_IMPL                        25                                       
STATE_TRANSITION_EVENT                 27                                       
JWFWF_SVR19090WLSTORE                  31                                       
JWFWF_SVR29090WLSTORE                  31                                       
JEAWF_SVR19090WLSTORE                  36                                       
JEAWF_SVR29090WLSTORE                  36                                       
REF_SCREEN                             37                                       
XML_REPOSITORY                         39                                       
TASKS_IN_PROJ_TMPLT                    44                                       
PROJ_TMPLT_PARM                        46                                       
SAMPNODE2_SVR8080WLSTORE               49                                       
SAMPNODE1_SVR8080WLSTORE               49                                       
PROJ_TMPLT_IMPL_PARM                   59                                       
DM_VOICE_REPORT_SUB_FAILURE            60                                       
ACTIONS_IN_TASK_TMPLT                  66                                       
DM_SERVICE_CODES                       69                                       
DM_EMTA_SERVICE_CODES                  69                                       
STATE_ACTION                           76                                       
ACTION_TMPLT                           77                                       
PARM_PERMITTED_VAL                     83                                       
REF_STATUS                             86                                       
REF_CLASS                              90                                       
REF_TASK_TYPE                          99                                       
SVC                                   104                                       
REF_OBJECT_TYP                        109                                       
PROCESS_DEF_DETAILS                   114                                       
STATE_TRANSITION                      122                                       
SRC_ACTION_PARM                       124                                       
SUBNTWK                               244                                       
LINK                                  245                                       
REF_PARM                              245                                       
WRK_UNIQUE_PARM                       257                                       
DM_ISP_REPORT_SUB_FAILURE             265                                       
ACTION_TMPLT_PARM                     294                                       
SUBNTWK_PARM                          302                                       
DM_MSO_ACCOUNTS_RUN1                  612                                       
DM_MSO_ACCOUNTS                       740                                       
DM_HSD_REPORT_SUB_FAILURE             849                                       
SVC_ACTION                            954                                       
SMP_ACTIVE_RUN                       1071                                       
MANUAL_TASK                          5825                                       
PARM                                 6480                                       
SUB_ORDR_ITEM_PARM                   7121                                       
SUB_OBJ_ENQ                          9950                                       
MANUAL_TASK_PARM                    20774                                       
SUB_SVC_PLAT_STAGE                  35563                                       
SUB_SVC_NTWK_STAGE                  78390                                       

DM_VOICE_SUB_LOG                   129732                                       
DM_DIAL_TONE                       129860                                       
DM_EMTA_DEVICE_CONTROL             129876                                       
DM_DIAL_TONE_SUB_SVC_ID            130191                                       
DM_VOICE_SUB                       130621                                       
DM_ISP_SUB_LOG                     161344                                       
DM_ISP_SUB                         161632                                       
DM_ISP_CONTROL                     161940                                       
DM_PRIMARY_USER_ACCESS             240876                                       
DM_PRIMARY_EMAIL                   240876                                       
DM_PERSONAL_WEBSPACE               240876                                       
DM_PASSWORD                        240876                                       
DM_PW_AS                           241435                                       
DM_CM_DEVICE_CONTROL               253876                                       
DM_HSD_SUB_LOG                     255285                                       
DM_SUBSCRIBER                      256804                                       
DM_V_SUBSCRIBER_DETAILS            259384                                       
DM_SUBSCRIBER_DETAILS              259772                                       
DM_E_N2P_STATUS                    259927                                       
DM_V_N2P_STATUS                    260130                                       
DM_E_SUBSCRIBER_DETAILS            260544                                       
DM_V_DEVICE_DETAILS                260745                                       
DM_N2P_STATUS                      260806                                       
DM_DEVICE_DETAILS                  261597                                       
EMAIL                              266178                                       
DM_VOICE_PORT_SUB_SVC_ID           270936                                       
LOCATION                           307658                                       
SUB_ADDR                           312951                                       
SUB_CONTACT                        315184                                       
SUB                                317952                                       
SUB_SVC_ASSOC                      446728                                       
ROOT_INSTANCE                      606736                                       
PROCESS_DEF                        610620                                       
SUB_ORDR                           873702                                       
SUB_CONTACT_PARM                   937361                                       
WRK_LOCK                          1049106                                       
DEPENDENCY_LINK                   1169794                                       
SUB_PARM                          1238674                                       
ORDR_ITEM_ASSOC_CHG               1470356                                       
SUB_SVC_DELIVERY_PLAT             1489911                                       
LOCATION_DTL                      1836344                                       
CONTROL_ATTR                      2013196                                       
INSTANCE                          2396626                                       
SUB_SVC_ADDR                      2586773                                       
SUB_SVC_PARM_DEPY                 2875073                                       
LINE_ITEM_DEPY                    3018825                                       
SUB_ORDR_PARM                     3137319                                       
SUB_SVC_NTWK                      3546119                                       
ORDR_ITEM_ENTITY_CHG              3768594                                       
SUB_SVC                           3969210                                       
SUB_ORDR_ITEM                     4785180                                       
SUB_SVC_PARM                     14937278                                       
OUTPUT_PARMS                     15420012                                       
CONTROL                          17306356                                       
VARIABLE                         44118443                                       
INPUT_PARMS                      50473078                                       
