insert into system_cmts_map values ('Billings','blnmt001cm1');
insert into system_cmts_map values ('Billings','blnmt002cm1');
insert into system_cmts_map values ('Billings','blnmt003cm1');
insert into system_cmts_map values ('Billings','blnmt004cm1');
insert into system_cmts_map values ('Billings','blnmt001cmc');
insert into system_cmts_map values ('Bozeman','ancmt001cm1');
insert into system_cmts_map values ('Bozeman','butmt001cm1');
insert into system_cmts_map values ('Bozeman','butmt002cm1');
insert into system_cmts_map values ('Bozeman','bzmmt001cm1');
insert into system_cmts_map values ('Bozeman','bzmmt002cm1');
insert into system_cmts_map values ('Bozeman','bzmmt001cmc');
insert into system_cmts_map values ('Bozeman','dlgmt001cm1');
insert into system_cmts_map values ('Bozeman','dllmt001cm1');
insert into system_cmts_map values ('Bozeman','lvtmt001cm1');
insert into system_cmts_map values ('Canon City','almco001cm1');
insert into system_cmts_map values ('Canon City','bnvco001cm1');
insert into system_cmts_map values ('Canon City','cacco001cm1');
insert into system_cmts_map values ('Canon City','ldvco001cm1');
insert into system_cmts_map values ('Canon City','ljnco001cm1');
insert into system_cmts_map values ('Canon City','salco001cm1');
insert into system_cmts_map values ('Canon City','wlbco001cm1');
insert into system_cmts_map values ('Casper','cspwy001cm1');
insert into system_cmts_map values ('Casper','cspwy002cm1');
insert into system_cmts_map values ('Casper','cspwy001cmc');
insert into system_cmts_map values ('Casper','rwlwy001cm1');
insert into system_cmts_map values ('Cedar City','cdcut001cm1');
insert into system_cmts_map values ('Cheyenne','chywy001cm1');
insert into system_cmts_map values ('Cheyenne','chywy002cm1');
insert into system_cmts_map values ('Cheyenne','chywy003cm1');
insert into system_cmts_map values ('Cheyenne','chywy004cm1');
insert into system_cmts_map values ('Cody','codwy001cm1');
insert into system_cmts_map values ('Cody','powwy001cm1');
insert into system_cmts_map values ('Craig','craco001cm1');
insert into system_cmts_map values ('Durango','durco001cm1');
insert into system_cmts_map values ('Ft Morgan','ftmco001cm1');
insert into system_cmts_map values ('Gillette','bflwy001cm1');
insert into system_cmts_map values ('Gillette','gltwy001cm1');
insert into system_cmts_map values ('Gillette','gltwy002cm1');
insert into system_cmts_map values ('Grand Junction','gdjco001cm1');
insert into system_cmts_map values ('Grand Junction','gdjco002cm1');
insert into system_cmts_map values ('Grand Junction','gdjco003cm1');
insert into system_cmts_map values ('Grand Junction','gdjco004cm1');
insert into system_cmts_map values ('Grand Junction','gdjco001cmc');
insert into system_cmts_map values ('Great Falls','ctbmt001cm1');
insert into system_cmts_map values ('Great Falls','grfmt001cm1');
insert into system_cmts_map values ('Great Falls','grfmt002cm1');
insert into system_cmts_map values ('Great Falls','grfmt003cm1');
insert into system_cmts_map values ('Havre','havmt001cm1');
insert into system_cmts_map values ('Helena','hlnmt001cm1');
insert into system_cmts_map values ('Helena','hlnmt002cm1');
insert into system_cmts_map values ('Jackson','jcswy001cm1');
insert into system_cmts_map values ('Kalispell','klsmt001cm1');
insert into system_cmts_map values ('Kalispell','klsmt002cm1');
insert into system_cmts_map values ('Kalispell','plsmt001cm1');
insert into system_cmts_map values ('Laramie','larwy001cm1');
insert into system_cmts_map values ('Missoula','hmtmt001cm1');
insert into system_cmts_map values ('Missoula','mslmt001cm1');
insert into system_cmts_map values ('Missoula','mslmt002cm1');
insert into system_cmts_map values ('Missoula','mslmt003cmc');
insert into system_cmts_map values ('Montrose','delco001cm1');
insert into system_cmts_map values ('Montrose','gdjco001cm1');
insert into system_cmts_map values ('Montrose','mtrco001cm1');
insert into system_cmts_map values ('Riverton','grywy001cm1');
insert into system_cmts_map values ('Riverton','lndwy001cm1');
insert into system_cmts_map values ('Riverton','rvtwy001cm1');
insert into system_cmts_map values ('Riverton','thrwy001cm1');
insert into system_cmts_map values ('Riverton','wrlwy001cm1');
insert into system_cmts_map values ('Sheridan','csrwy001cm1');
insert into system_cmts_map values ('Sterling','stnco001cm1');
insert into system_cmts_map values ('Vernal','vrnut001cm1');
