exec dbms_job.remove(10);
exec dbms_job.remove(11);
exec dbms_job.remove(12);
exec dbms_job.remove(8);
exec dbms_job.remove(9);
exec dbms_job.remove(13);
exec dbms_job.remove(28);
exec dbms_job.remove(48);
exec dbms_job.remove(49);
