Data Migration:
We require following Data Base pre-requisites for running Data Migration on all data bases.
  DEFAULT TABLESPACE BRESNAN
  ACCOUNT UNLOCK;
  GRANT CONNECT TO BRESNANDEV3CM;
  GRANT DEV_USER TO BRESNANDEV3CM;
  GRANT EXECUTE_CATALOG_ROLE TO BRESNANDEV3CM;
  ALTER USER BRESNANDEV3CM DEFAULT ROLE ALL;

GRANT SELECT ANY TABLE TO BRESNANDEV3CM;
GRANT CREATE ANY DIRECTORY TO BRESNANDEV3CM;
GRANT SELECT ANY DICTIONARY TO BRESNANDEV3CM;
GRANT CREATE PROCEDURE TO BRESNANDEV3CM;
GRANT CREATE VIEW TO BRESNANDEV3CM;
GRANT CREATE SYNONYM TO BRESNANDEV3CM;
GRANT CREATE ANY TABLE TO BRESNANDEV3CM;
GRANT UNLIMITED TABLESPACE TO BRESNANDEV3CM;
GRANT CREATE TRIGGER TO BRESNANDEV3CM;
GRANT CREATE SEQUENCE TO BRESNANDEV3CM;
GRANT CREATE TYPE TO BRESNANDEV3CM;
  ALTER USER BRESNANDEV3CM
    QUOTA UNLIMITED ON BRESNAN;
sga_target 6524288000
pga_aggregate_target 6524288000
Oracle server Disk space should be 100 GB minimum.
Oracle data base UNDO table space should be 10 GB minimum.
