REM SPCRPT4.SQL
REM 5/4/00 J. ADAMS
REM THIS SCRIPT PRODUCES THE SAME RESULTS AS SPCRPT3.SQL
REM BUT COMPUTES SUMS ON TOTAL SPACE AND TOTAL FREE SPACE.  

COLUMN NAME              FORMAT A15
COLUMN TOTAL             FORMAT 999,999,999,999 
COLUMN FREE              FORMAT 999,999,999,999
COLUMN PCT_FREE          FORMAT 999
COLUMN FRAG              FORMAT 99,999
COLUMN BIGGEST_FRAGMENT  FORMAT 999,999,999,999
set line 100

rem BREAK ON REPORT
COMPUTE SUM OF TOTAL ON REPORT
COMPUTE SUM OF FREE ON REPORT

SPOOL space_report.log

SELECT SYSDATE FROM DUAL;

SELECT NAME "DATABASE" FROM V$DATABASE;

SELECT TABLESPACE_NAME NAME, TOTAL, FREE,
       ROUND((FREE/TOTAL)*100,1) PCT_FREE,
       FRAGMENTS, BIGGEST_FRAGMENT
FROM(SELECT TABLESPACE_NAME, SUM(BYTES) TOTAL
       FROM SYS.DBA_DATA_FILES
     GROUP BY TABLESPACE_NAME),
    (SELECT TABLESPACE_NAME TS_NAME,
     SUM(BYTES) FREE, MAX(BYTES) BIGGEST_FRAGMENT, 
     COUNT(TABLESPACE_NAME) FRAGMENTS
       FROM SYS.DBA_FREE_SPACE
     GROUP BY TABLESPACE_NAME)
WHERE TABLESPACE_NAME = TS_NAME;
     
SPOOL OFF


exit
